version: '3.8'

services:

  employee-crm-backend:
    container_name: employee-crm-backend
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/var/www/apps/employee-crm/backend
